apiVersion: v1
kind: Service
metadata:
  name: victor-torreblanca-40-fe-service
  namespace: victor-torreblanca-40-namespace
spec:
  type: NodePort
  selector:
    app: victor-torreblanca-40-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30040
