name: SonarQube Analysis - Frontend

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests with ChromeHeadless
        run: |
          npm install --save-dev karma-chrome-launcher
          npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless || true
        
      - name: SonarQube Scan
        env:
          SONATOR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=victortorreblancafranco \
            -Dsonar.projectKey=victortorreblancafranco_AS241S5_AEJ_40-fe \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
